<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- stereo camera macro uses wge100_camera macros -->
  <include filename="$(find pr2_description)/urdf/sensors/wge100_camera.urdf.xacro" />

  <include filename="$(find pr2_description)/urdf/sensors/stereo_camera.gazebo.xacro" />

  <property name="stereo_size_x" value="0.005" />
  <property name="stereo_size_y" value="0.010" />
  <property name="stereo_size_z" value="0.005" />
  <property name="stereo_center_box_center_offset_x" value="0.00" />
  <property name="stereo_center_box_center_offset_z" value="0.05" />
  <property name="stereo_dx" value="0.00" />
  <property name="stereo_dy" value="-0.09" /> <!-- +y to the left -->
  <property name="stereo_dz" value="0.00" />
  <property name="stereo_rx" value="0.00" />
  <property name="stereo_ry" value="0.00" />
  <property name="stereo_rz" value="0.00" />

  <!-- this macro is used for creating wide and narrow double stereo camera links -->
  <xacro:macro name="stereo_camera_v0" params="name parent focal_length hfov *origin">
    
    <joint name="${name}_frame_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925" />
      </inertial>

      <visual>
        <origin xyz="${stereo_center_box_center_offset_x} 0 ${stereo_center_box_center_offset_z}" rpy="0 0 0" />
        <geometry>
          <box size="${stereo_size_x} ${stereo_size_y} ${stereo_size_z}" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision>
        <origin xyz="${stereo_center_box_center_offset_x} 0 ${stereo_center_box_center_offset_z}" rpy="0 0 0" />
        <geometry>
          <box size="${stereo_size_x} ${stereo_size_y} ${stereo_size_z}" />
        </geometry>
      </collision>
      
    </link>

    <joint name="${name}_optical_frame_joint" type="fixed">
      <origin xyz="${cal_stereo_x}            ${0.045+cal_stereo_y}   ${.0305+cal_stereo_z}" rpy="${-M_PI/2+cal_stereo_roll} ${0.0+cal_stereo_pitch} ${-M_PI/2+cal_stereo_yaw}" />
      <parent link="${name}_link"/>
      <child link="${name}_optical_frame"/>
    </joint>
    <link name="${name}_optical_frame" type="camera">

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>

    </link>


    <!-- stereo left camera -->
    <xacro:wge100_camera_v0 name="${name}_l_stereo_camera" topic_name="${name}/left_image"
                            parent="${name}_optical_frame"
                            hfov="${hfov}" focal_length="${focal_length}">
      <origin xyz="0 0 0" rpy="0 ${-M_PI/2} ${M_PI/2}" />
    </xacro:wge100_camera_v0>

    <!-- stereo right camera -->
    <xacro:wge100_camera_v0 name="${name}_r_stereo_camera" topic_name="${name}/right_image"
                            parent="${name}_l_stereo_camera_frame"
                            hfov="${hfov}" focal_length="${focal_length}">
      <origin xyz="${stereo_dx} ${stereo_dy} ${stereo_dz}" rpy="${stereo_rx} ${stereo_ry} ${stereo_rz}" />
    </xacro:wge100_camera_v0>

    <!-- extensions -->
    <xacro:stereo_camera_gazebo_v0 name="${name}" focal_length="${focal_length}" hfov="${hfov}" />

  </xacro:macro>
</robot>
