<?xml version="1.0"?>
<robot name="hcb">
  
  <!-- Include file with calibration parameters -->
  <include filename="$(find pr2_defs)/calibration/default_cal.xml" />
  
  <!-- declare the path where all models/textures/materials are stored -->
  <resource type="stl_meshes" location="$(find pr2_defs)/meshes"/>
  <resource type="ogre"       location="$(find pr2_ogre)/Media/models"/>
  
  <include filename="$(find pr2_defs)/defs/head/alpha2_head_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/head/head_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/head/prosilica_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/gazebo/gazebo_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/materials.urdf.xacro" />

  <!-- Make base joint for visualization -->
  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0.53" rpy="0 0 0" />
    <parent link="world" />
    <child link="base_link" />
  </joint>
  <link name="base_link">
    <inertial>
      <mass value="100" />
      <origin xyz=" 0 0 0 " />
      <inertia ixx="100"  ixy="0"  ixz="0" iyy="100" iyz="0" izz="100" />
    </inertial> 
    <visual>
      <!-- 1.06m above ground -->
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry name="unit_box">
	<box size=".6 0.45 1.06" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0 0 0" rpy="0.0 0.0 0.0 " />
      <geometry name="box_link_collision_geom">
        <box size="0.6 0.45 1.06" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>
  
  <!-- These dimensions need to be checked -->
  <pr2_head name="head" parent="base_link">
    <!-- 213mm above tilt plate. Pan/tilt intersect is origin. -->
    <origin xyz="${cal_head_x + 0.13}    ${cal_head_y}     ${.53 + 0.213 + cal_head_z}"
            rpy="${cal_head_roll} ${cal_head_pitch} ${cal_head_yaw}" />
  </pr2_head>

  <pr2_tilting_laser_alpha2 name="laser_tilt" parent="base_link">
    <!-- Was 0.11m forward of head pan, now 115 mm on HCC -->
    <!-- 66.5mm above head tilt plate -->
    <origin xyz="${0.115 + 0.13} 0 ${0.0665 + .53}" rpy="0 0 0" />
  </pr2_tilting_laser_alpha2>

  <!-- Camera package: double stereo, prosilica -->
  <pr2_head_sensor_package name="sensor_mount" hd_name="high_def" 
			   stereo_name="double_stereo" 
			   parent="head_plate_frame">
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
  </pr2_head_sensor_package>

</robot>
