<?xml version="1.0"?>
<robot name="PRE">
  
  <!-- Include file with calibration parameters -->
  <include filename="$(find pr2_defs)/calibration/pre_cal.xml" />
  
  <!-- declare the path where all models/textures/materials are stored -->
  <resource type="stl_meshes" location="$(find pr2_defs)/meshes"/>
  <resource type="ogre"       location="$(find pr2_ogre)/Media/models"/>
  
  <include filename="$(find pr2_defs)/defs/arm/arm_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/gripper/gripper_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/head/alpha2_head_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/body/body_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/base/alpha2_base_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/head/prosilica_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/gazebo/gazebo_defs.urdf.xacro" />
  <include filename="$(find pr2_defs)/defs/materials.urdf.xacro" />

  <!-- New casters have different encoder ticks, gear ratios -->
  <pr2_base_alpha2 name="base" >
    <origin xyz="0 0 0.051" rpy="0 0 0" /> 
  </pr2_base_alpha2>
    
  <!-- Reverting to old casters while Alpha 2's are in the shop -->
  <!--pr2_base name="base">
    <origin xyz="0 0 0.051" rpy="0 0 0" />
  </pr2_base-->

  <pr2_torso name="torso_lift" parent="base_link">
    <origin xyz="-0.05 0 0.739675" rpy="0 0 0" />
  </pr2_torso>

  <!-- Alpha 2.0b head installed 4/24/09 -->
  <!-- Tilt motor replaced with A2 motor 7/22 -->
  <pr2_head_alpha2 name="head" parent="torso_lift_link">
    <!--origin xyz="-0.01 0 0.3815" rpy="0 0 0" /-->
    <origin xyz="${cal_head_x - 0.01}    ${cal_head_y}     ${0.3915+cal_head_z}"
            rpy="${cal_head_roll} ${cal_head_pitch} ${cal_head_yaw}" />
  </pr2_head_alpha2>

  <!-- Alpha 2.0 laser tilt installed 4/3/09 -->
  <pr2_tilting_laser_alpha2 name="laser_tilt" parent="torso_lift_link">
    <!--origin xyz="0.1 0 0.19525" rpy="0 0 0" /-->
    <origin xyz="0.1 0 0.235" rpy="0 0 0" />
  </pr2_tilting_laser_alpha2>

  <!-- Camera package: double stereo, prosilica -->
  <pr2_head_sensor_package name="sensor_mount" hd_name="high_def" 
			   stereo_name="double_stereo" 
			   parent="head_plate_frame">
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
  </pr2_head_sensor_package>

  <pr2_arm side="r" reflect="-1" parent="torso_lift_link">
    <origin xyz="0 -0.188 0.0" rpy="0 0 0" />
  </pr2_arm>
  <pr2_gripper screw_reduction="${2.0/1000.0}" gear_ratio="${29.16}" side="r" parent="r_wrist_roll_link" >
    <origin xyz="0 0 0" rpy="0 0 0" />
  </pr2_gripper>

  <pr2_arm side="l" reflect="1" parent="torso_lift_link">
    <origin xyz="0.0 0.188 0.0" rpy="0 0 0" />
  </pr2_arm>
  <pr2_gripper screw_reduction="${2.0/1000.0}" gear_ratio="${29.16}" side="l" parent="l_wrist_roll_link" >
    <origin xyz="0 0 0" rpy="0 0 0" />
  </pr2_gripper>

  <!-- Kinematic chains -->
  <chain root="torso_lift_link" tip="l_wrist_roll_link" />
  <chain root="torso_lift_link" tip="r_wrist_roll_link" />

</robot>
